spring:
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  datasource:
    username: Citronix
    password:
    url: jdbc:postgresql://localhost:5432/Citronix

server:
  port: 8081


