spring:
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  server:
    port: 8081
  datasource:
    username: Citronix
    password:
    url: jdbc:postgresql://localhost:5432/Citronix

